"""Marcus — Traffic Manager agent.

Creates job records, tracks state transitions, monitors loop counts,
and triggers escalations. No creative decisions — pure operations.
Uses Haiku for lightweight state reasoning when needed.
"""

from typing import Any

from backend.agents.base import AgentError, BaseAgent
from backend.config import settings
from backend.models import Job


class MarcusAgent(BaseAgent):
    """Traffic manager — maintains job state and enforces loop limits.

    Marcus is the bookkeeper. Every state transition flows through him
    so there's a single source of truth for where a job stands.
    """

    name = "marcus"
    model = "haiku"
    system_prompt = (
        "You are Marcus, a traffic manager at a creative studio.\n\n"
        "Your job is purely operational:\n"
        "- Create job records with unique IDs\n"
        "- Track job status through the pipeline\n"
        "- Monitor loop counts (QA loops, revision loops)\n"
        "- Trigger escalations when loop limits are breached\n"
        "- Log all state changes\n\n"
        "You do not make creative decisions. You do not communicate with clients.\n"
        "You maintain order. That is your entire function."
    )

    # Valid status transitions — enforced to prevent state corruption.
    _VALID_TRANSITIONS: dict[str, set[str]] = {
        "pending": {"validating"},
        "validating": {"compositing", "failed", "escalated"},
        "compositing": {"qa", "failed", "escalated"},
        "qa": {"qa", "review", "compositing", "failed", "escalated"},
        "review": {"operator_review", "compositing", "failed", "escalated"},
        "operator_review": {"approved", "compositing", "escalated"},
        "approved": {"delivered"},
        "delivered": set(),
        "failed": set(),
        "escalated": {"compositing", "failed"},
    }

    async def execute(
        self, job: Job, input_data: dict[str, Any]
    ) -> dict[str, Any]:
        """Route to the requested operation based on input_data['action'].

        Marcus doesn't need LLM calls for most operations — state
        management is deterministic. LLM is reserved for edge cases
        where judgment is needed (not in POC).
        """
        action = input_data.get("action", "create")

        if action == "create":
            return await self._create_job(job, input_data)
        elif action == "update_status":
            return await self._update_status(
                job, input_data["new_status"], input_data.get("reason", "")
            )
        elif action == "increment_qa":
            return await self._increment_qa(job)
        elif action == "increment_revision":
            return await self._increment_revision(job)
        else:
            raise AgentError(self.name, "execute", f"Unknown action: {action}")

    async def _create_job(
        self, job: Job, input_data: dict[str, Any]
    ) -> dict[str, Any]:
        """Initialise a new job with brief data and conversation link.

        Job ID is auto-generated by the model's default factory.
        Marcus just fills in the metadata from the parsed brief.
        """
        job.brand_name = input_data.get("brand_name", "")
        job.job_title = input_data.get("job_title", "")
        job.conversation_id = input_data.get("conversation_id", "")
        job.brief_json = input_data.get("brief_json", {})
        job.output_sizes = input_data.get("output_sizes", [])
        job.status = "pending"

        await self._session.flush()

        return {
            "job_id": job.id,
            "status": job.status,
        }

    async def _update_status(
        self, job: Job, new_status: str, reason: str
    ) -> dict[str, Any]:
        """Transition job to a new status with validation.

        Rejects invalid transitions to prevent state corruption — a job
        in 'delivered' state should never go back to 'compositing'.
        """
        valid_next = self._VALID_TRANSITIONS.get(job.status, set())
        if new_status not in valid_next:
            raise AgentError(
                self.name,
                "update_status",
                f"Invalid transition: {job.status} → {new_status}",
            )

        job.status = new_status
        if reason:
            job.error_log += f"\n[{new_status}] {reason}"

        await self._session.flush()

        return {"job_id": job.id, "status": new_status, "reason": reason}

    async def _increment_qa(self, job: Job) -> dict[str, Any]:
        """Bump QA attempt count and escalate if limit reached.

        Max attempts configurable via COST_CEILING — defaults to 3.
        After 3 failed QA loops, the job needs human intervention.
        """
        job.compliance_attempts += 1
        should_escalate = job.compliance_attempts >= settings.max_qa_attempts

        if should_escalate:
            job.status = "escalated"
            job.error_log += "\n[escalated] qa_failed: max QA attempts reached"

        await self._session.flush()

        return {
            "job_id": job.id,
            "compliance_attempts": job.compliance_attempts,
            "escalated": should_escalate,
            "reason": "qa_failed" if should_escalate else "",
        }

    async def _increment_revision(self, job: Job) -> dict[str, Any]:
        """Bump user revision count and escalate if limit reached.

        Max 2 revision rounds — after that, the operator takes over
        to prevent endless back-and-forth.
        """
        job.user_revision_count += 1
        should_escalate = job.user_revision_count >= settings.max_user_revisions

        if should_escalate:
            job.status = "escalated"
            job.error_log += (
                "\n[escalated] revision_limit: max user revisions reached"
            )

        await self._session.flush()

        return {
            "job_id": job.id,
            "user_revision_count": job.user_revision_count,
            "escalated": should_escalate,
            "reason": "revision_limit" if should_escalate else "",
        }
